# Generated by Django 5.0 on 2023-12-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='Name',
        ),
    ]
